seed: 1777777
resize_shape:
  - 256
  - 256
augmentation_p: 0.1
color_jitter: 0.37
random_rotation_angle: 15
normalize_means:
  - 0.50297405
  - 0.54711632
  - 0.71049083
normalize_stds:
  - 0.18653496
  - 0.17118206
  - 0.17080363
dataset_name: ISIC-2018
dataset_path: ./datasets/ISIC-2018
gt_format: '{}_mask.jpg'
batch_size: 32
num_workers: 2
model_name: PMFSNet
in_channels: 3
classes: 2
index_to_class_dict:
  0: background
  1: foreground
resume: null
pretrain: null

# Optimizer
optimizer_config:
  name: AdamW
  optimizer:
    lr: 1e-4
    weight_decay: 0.000001

# lr_scheduler
lr_scheduler_config:
  name: CosineAnnealingWarmRestarts
  scheduler: # For scheduler params you can find it at torch.optim.lr_scheduler.*
    T_0: 5
    T_mult: 5
    eta_min: 0
    last_epoch: -1
    verbose: "deprecated"
  lightning_config: Null # For lightning config you can find it at https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.core.LightningModule.html#lightning.pytorch.core.LightningModule.configure_optimizers
gamma: 0.9582311026945434

loss_function_name: DiceLoss

run_dir: ./runs
end_epoch: 250

use_image_transform: False
result_path: ./results